### ISSUE TITLE
require returning "Cannot find module" error after updating to version 0.2.6

### ISSUE THREAD

**Issue by privman** [PinchProject/Node-GCMService#4]
Working fine with version 0.2.4, but after updating to 0.2.6, require("node-gcm-service") returns the following error:
Error: Cannot find module 'node-gcm-service'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at repl:1:2
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)

Reproduced with node 0.10.12 on Mac OS X 10.8 and with node 0.10.16 on Ubuntu 10.04.
After rolling back to 0.2.4 works fine again.

**Comment by privman** [comment]
$ npm list
npm WARN package.json assert-plus@0.1.2 No repository field.
npm WARN package.json ctype@0.5.2 No repository field.
/c/src/testGcm
└─┬ node-gcm-service@0.2.6
  ├── async@0.2.9
  ├── attempt@1.0.0
  ├── debug@0.7.2
  └─┬ request@2.25.0
    ├── aws-sign@0.3.0
    ├── cookie-jar@0.3.0
    ├── forever-agent@0.5.0
    ├─┬ form-data@0.1.1
    │ └─┬ combined-stream@0.0.4
    │   └── delayed-stream@0.0.5
    ├─┬ hawk@1.0.0
    │ ├── boom@0.4.2
    │ ├── cryptiles@0.2.2
    │ ├── hoek@0.9.1
    │ └── sntp@0.2.4
    ├─┬ http-signature@0.10.0
    │ ├── asn1@0.1.11
    │ ├── assert-plus@0.1.2
    │ └── ctype@0.5.2
    ├── json-stringify-safe@5.0.0
    ├── mime@1.2.11
    ├── node-uuid@1.4.1
    ├── oauth-sign@0.3.0
    ├── qs@0.6.5
    └── tunnel-agent@0.3.0

**Comment by ghost** [comment]
Bug fixed 76de1dde2a1d830901ccffe9832473aa3b4d8340
